<?php

declare(strict_types=1);

namespace Atfm\Allocator;

/**
 * PERTI-compatible composite flight key.
 *
 * Mirrors the format generated by sp_Adl_RefreshFromVatsim_Normalized.sql
 * at line 161:
 *
 *   cid | callsign | departure | arrival | deptime
 *
 * Five pipe-separated fields. NULLs become empty strings. Deterministic
 * from observed flight-plan data. A new flight_key is generated whenever
 * any of the five fields change, which naturally creates a fresh flight
 * record on refile (by design).
 *
 * See docs/ARCHITECTURE.md §4.4 and docs/GLOSSARY.md "flight_key".
 */
final class FlightKey
{
    /**
     * @param array $pilot A single pilot entry from data.vatsim.net
     */
    public static function fromVatsimPilot(array $pilot): string
    {
        $fp = $pilot['flight_plan'] ?? [];
        $deptime = (string) ($fp['deptime'] ?? '');
        $remarks = (string) ($fp['remarks'] ?? '');

        // Extract DOF from remarks (ICAO standard: DOF/YYMMDD).
        // Without DOF, a pilot filing "1500" today produces the same key
        // as the same pilot filing "1500" yesterday — causing stale record
        // reuse. The DOF disambiguates.
        $dof = '';
        if (preg_match('/\bDOF\/(\d{6})\b/', $remarks, $m)) {
            $dof = $m[1]; // YYMMDD
        } else {
            // Fallback: use today's date in YYMMDD. If the pilot doesn't
            // file a DOF, we assume it's today's flight. A reconnection
            // tomorrow with the same plan will get a new key.
            $dof = gmdate('ymd');
        }

        return implode('|', [
            (int) ($pilot['cid'] ?? 0),
            (string) ($pilot['callsign'] ?? ''),
            strtoupper((string) ($fp['departure'] ?? '')),
            strtoupper((string) ($fp['arrival'] ?? '')),
            $deptime . '/' . $dof,
        ]);
    }

    /**
     * Extract the CID (first component) from a flight_key.
     */
    public static function cid(string $flightKey): int
    {
        $parts = explode('|', $flightKey, 5);
        return (int) ($parts[0] ?? 0);
    }

    /**
     * Extract the callsign (second component).
     */
    public static function callsign(string $flightKey): string
    {
        $parts = explode('|', $flightKey, 5);
        return (string) ($parts[1] ?? '');
    }
}
