<?php

declare(strict_types=1);

namespace Atfm\Allocator;

/**
 * PERTI-compatible composite flight key.
 *
 * Mirrors the format generated by sp_Adl_RefreshFromVatsim_Normalized.sql
 * at line 161:
 *
 *   cid | callsign | departure | arrival | deptime
 *
 * Five pipe-separated fields. NULLs become empty strings. Deterministic
 * from observed flight-plan data. A new flight_key is generated whenever
 * any of the five fields change, which naturally creates a fresh flight
 * record on refile (by design).
 *
 * See docs/ARCHITECTURE.md §4.4 and docs/GLOSSARY.md "flight_key".
 */
final class FlightKey
{
    /**
     * @param array $pilot A single pilot entry from data.vatsim.net
     */
    public static function fromVatsimPilot(array $pilot): string
    {
        $fp = $pilot['flight_plan'] ?? [];

        return implode('|', [
            (int) ($pilot['cid'] ?? 0),
            (string) ($pilot['callsign'] ?? ''),
            strtoupper((string) ($fp['departure'] ?? '')),
            strtoupper((string) ($fp['arrival'] ?? '')),
            (string) ($fp['deptime'] ?? ''),
        ]);
    }

    /**
     * Extract the CID (first component) from a flight_key.
     */
    public static function cid(string $flightKey): int
    {
        $parts = explode('|', $flightKey, 5);
        return (int) ($parts[0] ?? 0);
    }

    /**
     * Extract the callsign (second component).
     */
    public static function callsign(string $flightKey): string
    {
        $parts = explode('|', $flightKey, 5);
        return (string) ($parts[1] ?? '');
    }
}
